#!/bin/bash

set -o errexit
set -o nounset

PROGRAM=$(basename $0)
SCRIPTDIR=$(dirname $0)

TMPDIR=$(mktemp -d -t $PROGRAM)
$SCRIPTDIR/generate_images $TMPDIR

DIFFDIR=$(grealpath --relative-to=. $SCRIPTDIR/../.diffs)

rm -r $DIFFDIR
mkdir -p $DIFFDIR
# Workaround bizarre issue, where the single command below doesn't work, in that it copies all files over.
# rsync -rc --compare-dest=master_images/ $TMPDIR/ diffs/
rsync -rc --compare-dest=$TMPDIR/ $SCRIPTDIR/master_images/ $DIFFDIR/
rsync -rc --existing $TMPDIR/ $DIFFDIR/
find $DIFFDIR -type d -depth -empty -exec rmdir "{}" \;
find $DIFFDIR -type f

rm -r $TMPDIR
