#!/bin/bash

set -o errexit
set -o nounset

SCRIPTDIR=$(dirname $0)

clang++ -std=c++1y -Weverything -ferror-limit=1 -ftemplate-backtrace-limit=1 -Wno-missing-prototypes -Wno-padded -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-disabled-macro-expansion -Wno-global-constructors -Wno-exit-time-destructors -Wno-float-equal -I/usr/local/opt/qt/include --system-header-prefix=QtGui/ --system-header-prefix=QtWidgets/ --system-header-prefix=boost/ -F/usr/local/opt/qt/lib -framework QtGui -framework QtCore -framework QtWidgets $SCRIPTDIR/rasterise_text.cxx -o $SCRIPTDIR/rasterise_text.out

OUTPUT_ROOT=${1:-$SCRIPTDIR/master_images}
mkdir -p $OUTPUT_ROOT

for i in $SCRIPTDIR/cases/*.txt; do
    j=${i#${SCRIPTDIR}/cases/}
    output_dir=$OUTPUT_ROOT/${j%.txt}
    mkdir -p $output_dir
    rm -f $output_dir/*
    $SCRIPTDIR/rasterise_text.out $i $output_dir
done
