#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

PROGRAM=$(basename $0)
SCRIPTDIR=$(dirname $0)

TMPDIR=$(mktemp -d -t $PROGRAM)
$SCRIPTDIR/generate_images $TMPDIR

ACTUALSDIR=$(grealpath --relative-to=. $SCRIPTDIR/../.actuals)

rm -rf $ACTUALSDIR
mkdir -p $ACTUALSDIR
# Workaround bizarre issue, where the single command below doesn't work, in that it copies all files over.
# rsync -rc --compare-dest=master_images/ $TMPDIR/ diffs/
rsync -=recursive --checksum --compare-dest=$TMPDIR/ $SCRIPTDIR/master_images/ $ACTUALSDIR/
rsync --recursive --checksum --existing $TMPDIR/ $ACTUALSDIR/
find $ACTUALSDIR -type d -depth -empty -exec rmdir "{}" \;
rm -f $ACTUALSDIR/.DS_Store

DIFFSDIR=$(grealpath --relative-to=. $SCRIPTDIR/../.diffs)
rm -rf $DIFFSDIR
mkdir -p $DIFFSDIR

for i in $(find $ACTUALSDIR -type f); do
    mkdir -p $(dirname $DIFFSDIR/${i#$ACTUALSDIR/})
    compare -compose src test/osx/master_images/${i#$ACTUALSDIR/} $i $DIFFSDIR/${i#$ACTUALSDIR/} || {
        RESULT=$?
        # ImageMagick compare return 0 for identical, 1 for different and 2 for error
        [ $RESULT -gt 1 ] && exit $RESULT
    }
done

rm -r $TMPDIR

find $DIFFSDIR -type f
