#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

PROGRAM=$(basename $0)
TMPDIR=$(mktemp -d -t $PROGRAM)

SCRIPTDIR=$(dirname $0)

rsync --recursive --checksum $1/ $TMPDIR/expected/

mkdir -p $TMPDIR/actual
$SCRIPTDIR/generate_images $TMPDIR/actual

mkdir -p $TMPDIR/diff

for actual in $(find $TMPDIR/actual -type f); do
    temp=${actual#${TMPDIR}}
    temp=${temp#/actual/}
    expected=$TMPDIR/expected/$temp
    diff=$TMPDIR/diff/$temp

    mkdir -p $(dirname $diff)

    if cmp --quiet $expected $actual; then
        continue
    fi

    compare -compose src $expected $actual $diff || {
        RESULT=$?
        # ImageMagick compare return 0 for identical, 1 for different and 2 for error
        [ $RESULT -gt 1 ] && exit $RESULT
    }
done

find $TMPDIR/diff -type f
